from itertools import product

import numpy as np
Coordinates = np.ndarray

class RayBeam:
    ORIGIN = np.zeros(3, dtype = np.int32)

    def __init__(self, source: np.ndarray, direction: np.ndarray):
        self.source = source
        self.direction = direction

    @staticmethod
    def colinear_distance(v1: Coordinates, v2: Coordinates):
        agreement = sum(1 for i in range(3) if v1[i] == v2[i])
        return v2 - v1 if agreement == 2 else RayBeam.ORIGIN

    def interrupted_by(self, that: Coordinates):
        # Check whether that - self.source is colinear with self.direction
        difference = that - self.source

        if np.array_equal(RayBeam.ORIGIN, difference):
            return False

        cross = np.linalg.cross(difference, self.direction)

        condition = np.dot(difference, self.direction) > 1 and np.array_equal(RayBeam.ORIGIN, cross)
        if condition != self.interrupted_by_array(that):
            raise Exception(f"INTERRUPTION inconsistency detected: {self} / {that}")

        return np.dot(difference, self.direction) > 1 and np.array_equal(RayBeam.ORIGIN, cross)

    def interrupted_by_array(self, that):
        return any(np.array_equal(pos, that) for pos in self.to_array())

    # TODO: expand to 3D.
    def intersected_by(self, that):
        relative_orientation = np.dot(self.direction, that.direction)

        report = f"INTERSECTION inconsistency detected: {self} / {that}\n"
        report += f"> Relative orientation : {relative_orientation}\n"
        report += f"> Beam 1 : {self.to_array()}\n"
        report += f"> Beam 2 : {that.to_array()}\n"

        # Based on the relative orientation, the source of the other beam must be located in the correct subspace.
        sigma = that.source - self.source
        cross = np.cross(self.direction, sigma)
        if relative_orientation == 0:
            # Beams are in orthogonal directions
            # Check that the source of the other beam lies in the subspace generated by the directions
            basis = self.direction - that.direction
            intra = np.all( (basis != 0) | (sigma == 0) )
            # Check that the source of the other beam lies in the positive quadrant of that subspace
            joint = np.sign(sigma) * np.sign(basis)
            pos_q = np.count_nonzero(joint < 0) == 0
            report += f"> Sigma : {sigma}\n"
            report += f"> Basis : {basis}\n"
            report += f"> Cross : {cross}\n"
            report += f"> Intra : {intra}\n"
            report += f"> Joint : {joint}\n"
            report += f"> Pos Q : {pos_q}\n"
            intersecting_rays = intra and pos_q
        else:
            # Beams are in identical or opposite directions
            # The source of the other beam must lie on the same line as the direction of this beam either way
            intersecting_rays = np.dot(cross, cross) == 0
            if relative_orientation == -1:
                # Beams are in opposite directions
                # The source of the other beam cannot be behind the source of this beam
                intersecting_rays = intersecting_rays and np.dot(self.direction, sigma) >= 0

        intersecting_arrays = self.intersected_by_array(that)
        if intersecting_rays != intersecting_arrays:
            report += f"> R:{intersecting_rays}/A:{intersecting_arrays}"
            raise Exception(report)

        return intersecting_rays

    def intersected_by_array(self, that):
        array1 = self.to_array()
        array2 = that.to_array()
        return any(np.array_equal(p1, p2) for p1, p2 in product(array1, array2))

    @staticmethod
    def __inner_determinant(v1: Coordinates, v2: Coordinates, v3: Coordinates):
        return np.linalg.det(
            np.column_stack( (v1, v2, v3) )
        )

    def to_array(self, length: int = 10):
        return [ self.source + i * self.direction for i in range(length) ]

    def __eq__(self, other):
        return np.array_equal(self.source, other.source) and np.array_equal(self.direction, other.direction)

    def __hash__(self):
        return hash(str(self))

    def __str__(self):
        return f"@{self.source}->{self.direction}"

    def __repr__(self):
        return str(self)